<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-6QJ44UQ" ignored="0" name="Test" tests="6" failures="1" timestamp="2022-07-14T00:05:05 IST" time="0.219" errors="0">
  <testcase name="test01" time="0.021" classname="com.demo.DemoTest"/>
  <testcase name="test02" time="0.008" classname="com.demo.DemoTest">
    <skipped/>
  </testcase> <!-- test02 -->
  <testcase name="test02" time="0.003" classname="com.demo.DemoTest">
    <skipped/>
  </testcase> <!-- test02 -->
  <testcase name="test02" time="0.005" classname="com.demo.DemoTest">
    <skipped/>
  </testcase> <!-- test02 -->
  <testcase name="test02" time="0.018" classname="com.demo.DemoTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.demo.DemoTest.test02(DemoTest.java:18)
at java.util.ArrayList.forEach(ArrayList.java:1249)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test02 -->
  <testcase name="test03" time="0.006" classname="com.demo.DemoTest">
    <skipped/>
  </testcase> <!-- test03 -->
</testsuite> <!-- Test -->
